# Site settings
title: Sonora Data
email: jonny@sonoradata.com
url: http://sonoradata.github.io
description: "BLE hyperlocal network in Tempe, AZ"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#19B5FE'
  links: '#219ab3'

# Footer settings
footer: Sonora Data, LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
